[package]
name = "sec_6"
version = "0.1.0"
authors = ["Yuto Mizutani <mizutani@fringe81.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
